/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-05-31 00:49:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header>\r\n");
      out.write("  <div class=\"default-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2\">\r\n");
      out.write("          <div class=\"logo\"> <a href=\"index.jsp\"><img src=\"assets/images/logg2.png\" alt=\"image\"/></a> </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-9 col-md-10\">\r\n");
      out.write("          <div class=\"header_info\">\r\n");
      out.write("            <div class=\"header_widgets\">\r\n");
      out.write("              <div class=\"circle_icon\"> <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> </div>\r\n");
      out.write("              <p class=\"uppercase_text\">For Support Mail us : </p>\r\n");
      out.write("              <a href=\"mailto:info@example.com\">bikerportal@portal.com</a> </div>\r\n");
      out.write("            <div class=\"header_widgets\">\r\n");
      out.write("              <div class=\"circle_icon\"> <i class=\"fa fa-phone\" aria-hidden=\"true\"></i> </div>\r\n");
      out.write("              <p class=\"uppercase_text\">Service Helpline Call Us: </p>\r\n");
      out.write("              <a href=\"tel:61-1234-5678-09\">+91-99876543210</a> </div>\r\n");
      out.write("            <div class=\"social-follow\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"http://www.facebook.com\"><i class=\"fa fa-facebook-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"https://www.twitter.com\"><i class=\"fa fa-twitter-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"https://www.linkedin.com\"><i class=\"fa fa-linkedin-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"https://www.google.com\"><i class=\"fa fa-google-plus-square\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"https://www.instagram.com/\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <c:choose>\r\n");
      out.write("            \t<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("            \t\t<div class=\"login_btn\"> <a href=\"#loginform\" class=\"btn btn-xs uppercase\" data-toggle=\"modal\" data-dismiss=\"modal\">Login / Register</a> </div>\r\n");
      out.write("            \t</c:when>\r\n");
      out.write("            \t<c:otherwise>\r\n");
      out.write("           \t\t\t<div>Welcome To Bike rental portal</div>\t\r\n");
      out.write("            \t</c:otherwise>\r\n");
      out.write("            </c:choose>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>    \r\n");
      out.write("             <nav id=\"navigation_bar\" class=\"navbar navbar-default\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("        <button id=\"menu_slide\" data-target=\"#navigation\" aria-expanded=\"false\" data-toggle=\"collapse\" class=\"navbar-toggle collapsed\" type=\"button\"> <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header_wrap\">\r\n");
      out.write("        <div class=\"user_login\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"dropdown\"> <a href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fa fa-user-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("            \r\n");
      out.write("            <sql:query dataSource = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${db}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" var = \"result\">\r\n");
      out.write("        \t    SELECT * from tblusers where FullName = '<c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessioScope.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>'  ;\r\n");
      out.write("     \t    </sql:query>\r\n");
      out.write(" \r\n");
      out.write("\t         <c:forEach var = \"row\" items = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result.rows}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t                <c:out value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.FullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t         </c:forEach>\r\n");
      out.write("\t         <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("              \t<c:choose>\r\n");
      out.write("            \t\t<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("            \t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">Profile Settings</a></li>\r\n");
      out.write("              \t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">Update Password</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">My Booking</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">Post a Testimonial</a></li>\r\n");
      out.write("          \t\t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">My Testimonial</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"#loginform\"  data-toggle=\"modal\" data-dismiss=\"modal\">Sign Out</a></li>\r\n");
      out.write("            \t\t</c:when>\r\n");
      out.write("            \t\t<c:otherwise>\r\n");
      out.write("           \t\t\t\t<li><a href=\"profile.jsp\">Profile Settings</a></li>\r\n");
      out.write("              \t\t\t<li><a href=\"update-password.jsp\">Update Password</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"my-booking.jsp\">My Booking</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"post-testimonial.jsp\">Post a Testimonial</a></li>\r\n");
      out.write("          \t\t\t\t<li><a href=\"my-testimonials.jsp\">My Testimonial</a></li>\r\n");
      out.write("            \t\t\t<li><a href=\"logout.jsp\">Sign Out</a></li>\t\r\n");
      out.write("            \t\t</c:otherwise>\r\n");
      out.write("            \t</c:choose>\r\n");
      out.write("            \t</ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_search\">\r\n");
      out.write("          <div id=\"search_toggle\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("          <form action=\"#\" method=\"get\" id=\"header-search-form\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search...\" class=\"form-control\">\r\n");
      out.write("            <button type=\"submit\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navigation\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("          <li><a href=\"index.jsp\">Home</a>    </li>\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"page.jsp?type=aboutus\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"bike-listing.jsp\">Bike Listing</a>\r\n");
      out.write("          <li><a href=\"page.jsp?type=faqs\">FAQs</a></li>\r\n");
      out.write("          <li><a href=\"contact-us.jsp\">Contact Us</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Navigation end -->\r\n");
      out.write("            \t\r\n");
      out.write("\t\t\r\n");
      out.write("</header>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
