/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-06-01 09:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.release();
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("     <!-- DataBase -->\r\n");
      out.write("\t ");
      if (_jspx_meth_sql_005fsetDataSource_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t <!-- /DataBase -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Bike Rental Portal | Admin Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Font awesome -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\t<!-- Sandstone Bootstrap CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- Bootstrap Datatables -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\t<!-- Bootstrap social button library -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap-social.css\">\r\n");
      out.write("\t<!-- Bootstrap select -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap-select.css\">\r\n");
      out.write("\t<!-- Bootstrap file input -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/fileinput.min.css\">\r\n");
      out.write("\t<!-- Awesome Bootstrap checkbox -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/awesome-bootstrap-checkbox.css\">\r\n");
      out.write("\t<!-- Admin Stye -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\"></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"brand clearfix\">\r\n");
      out.write("\t<a href=\"dashboard.jsp\" style=\"font-size: 20px;\">Bike Rental Portal | Admin Panel</a>  \r\n");
      out.write("\t\t<span class=\"menu-btn\"><i class=\"fa fa-bars\"></i></span>\r\n");
      out.write("\t\t<ul class=\"ts-profile-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"ts-account\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><img src=\"img/ts-avatar.jpg\" class=\"ts-avatar hidden-side\" alt=\"\"> Account <i class=\"fa fa-angle-down hidden-side\"></i></a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"change-password.jsp\">Change Password</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ts-main-content\">\r\n");
      out.write("\t\t<nav class=\"ts-sidebar\">\r\n");
      out.write("\t\t\t<ul class=\"ts-sidebar-menu\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"ts-label\">Main</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"dashboard.jsp\"><i class=\"fa fa-dashboard\"></i> Post A Bike</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"manage-booking.jsp\"><i class=\"fa fa-users\"></i> Manage Booking</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\t\r\n");
      out.write("\t\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"page-title\">Post A Bike</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">Basic Info</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("<form method=\"post\" class=\"form-horizontal\" enctype=\"multipart/form-data\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Vehicle Title<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<input type=\"text\" name=\"vehicletitle\" class=\"form-control\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Select Brand<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<select class=\"selectpicker\" name=\"brandname\" required>\r\n");
      out.write("<option value=\"\"> Select </option>\r\n");
      out.write("  ");
      if (_jspx_meth_sql_005fquery_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t        \r\n");
      out.write("\t         ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"hr-dashed\"></div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Vehical Overview<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-10\">\r\n");
      out.write("<textarea class=\"form-control\" name=\"vehicalorcview\" rows=\"3\" required></textarea>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Price Per Day(in INR)<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<input type=\"text\" name=\"priceperday\" class=\"form-control\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Select Fuel Type<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<select class=\"selectpicker\" name=\"fueltype\" required>\r\n");
      out.write("<option value=\"\"> Select </option>\r\n");
      out.write("\r\n");
      out.write("<option value=\"Petrol\">Petrol</option>\r\n");
      out.write("<option value=\"Diesel\">Diesel</option>\r\n");
      out.write("<option value=\"CNG\">CNG</option>\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Model Year<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<input type=\"text\" name=\"modelyear\" class=\"form-control\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<label class=\"col-sm-2 control-label\">Seating Capacity<span style=\"color:red\">*</span></label>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("<input type=\"text\" name=\"seatingcapacity\" class=\"form-control\" required>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"hr-dashed\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<div class=\"col-sm-12\">\r\n");
      out.write("<h4><b>Upload Images</b></h4>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("Image 1 <span style=\"color:red\">*</span><input type=\"file\" name=\"img1\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("Image 2<span style=\"color:red\">*</span><input type=\"file\" name=\"img2\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("Image 3<span style=\"color:red\">*</span><input type=\"file\" name=\"img3\" required>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("Image 4<span style=\"color:red\">*</span><input type=\"file\" name=\"img4\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">\r\n");
      out.write("Image 5<input type=\"file\" name=\"img5\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"hr-dashed\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("<div class=\"panel panel-default\">\r\n");
      out.write("<div class=\"panel-heading\">Accessories</div>\r\n");
      out.write("<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<div class=\"checkbox checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"antilockbrakingsys\" name=\"antilockbrakingsys\" value=\"1\">\r\n");
      out.write("<label for=\"antilockbrakingsys\"> AntiLock Braking System </label>\r\n");
      out.write("</div></div>\r\n");
      out.write("<div class=\"checkbox checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"brakeassist\" name=\"brakeassist\" value=\"1\">\r\n");
      out.write("<label for=\"brakeassist\"> Brake Assist </label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<div class=\"checkbox checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"powersteering\" name=\"powersteering\" value=\"1\">\r\n");
      out.write("<input type=\"checkbox\" id=\"powersteering\" name=\"powersteering\" value=\"1\">\r\n");
      out.write("<label for=\"inlineCheckbox5\"> Smooth Handling </label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<div class=\"checkbox h checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"centrallocking\" name=\"centrallocking\" value=\"1\">\r\n");
      out.write("<label for=\"centrallocking\">Central Locking</label>\r\n");
      out.write("</div></div>\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<div class=\"checkbox checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"crashcensor\" name=\"crashcensor\" value=\"1\">\r\n");
      out.write("<label for=\"crashcensor\"> Crash Sensor </label>\r\n");
      out.write("</div></div>\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<div class=\"checkbox checkbox-inline\">\r\n");
      out.write("<input type=\"checkbox\" id=\"leatherseats\" name=\"leatherseats\" value=\"1\">\r\n");
      out.write("<label for=\"leatherseats\"> Leather Seats </label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"reset\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" name=\"submit\" type=\"submit\">Save changes</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t<!-- Loading Scripts -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-select.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/Chart.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/fileinput.js\"></script>\r\n");
      out.write("\t<script src=\"js/chartData.js\"></script>\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sql_005fsetDataSource_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:setDataSource
    org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag _jspx_th_sql_005fsetDataSource_005f0 = (org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag) _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag.class);
    boolean _jspx_th_sql_005fsetDataSource_005f0_reused = false;
    try {
      _jspx_th_sql_005fsetDataSource_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fsetDataSource_005f0.setParent(null);
      // /admin/dashboard.jsp(6,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setVar("db");
      // /admin/dashboard.jsp(6,2) name = driver type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setDriver("com.mysql.jdbc.Driver");
      // /admin/dashboard.jsp(6,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUrl("jdbc:mysql://localhost/bikers_portal_db");
      // /admin/dashboard.jsp(6,2) name = user type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUser("root");
      // /admin/dashboard.jsp(6,2) name = password type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setPassword("");
      int _jspx_eval_sql_005fsetDataSource_005f0 = _jspx_th_sql_005fsetDataSource_005f0.doStartTag();
      if (_jspx_th_sql_005fsetDataSource_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.reuse(_jspx_th_sql_005fsetDataSource_005f0);
      _jspx_th_sql_005fsetDataSource_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fsetDataSource_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fsetDataSource_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sql_005fquery_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:query
    org.apache.taglibs.standard.tag.rt.sql.QueryTag _jspx_th_sql_005fquery_005f0 = (org.apache.taglibs.standard.tag.rt.sql.QueryTag) _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.QueryTag.class);
    boolean _jspx_th_sql_005fquery_005f0_reused = false;
    try {
      _jspx_th_sql_005fquery_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fquery_005f0.setParent(null);
      // /admin/dashboard.jsp(80,2) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setDataSource((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${db}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /admin/dashboard.jsp(80,2) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setVar("result");
      int[] _jspx_push_body_count_sql_005fquery_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sql_005fquery_005f0 = _jspx_th_sql_005fquery_005f0.doStartTag();
        if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_sql_005fquery_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fquery_005f0);
          }
          do {
            out.write("\r\n");
            out.write("        \t    select id,BrandName from tblbrands;\r\n");
            out.write("     \t    ");
            int evalDoAfterBody = _jspx_th_sql_005fquery_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_sql_005fquery_005f0[0]--;
          }
        }
        if (_jspx_th_sql_005fquery_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sql_005fquery_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sql_005fquery_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sql_005fquery_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fquery_005f0);
      _jspx_th_sql_005fquery_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fquery_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fquery_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/dashboard.jsp(84,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      // /admin/dashboard.jsp(84,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/dashboard.jsp(84,10) '${result.rows}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${result.rows}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t         \t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ row.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.BrandName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t         \t\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
